apiVersion: v1
kind: Service
metadata:
  name: stacked-pr-demo
  labels:
    app: stacked-pr-demo
spec:
  selector:
    app: stacked-pr-demo
  ports:
    - name: http
      port: 80
      targetPort: http