apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stacked-pr-demo
  labels:
    app: stacked-pr-demo
spec:
  selector:
    matchLabels:
      app: stacked-pr-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
